CREATE TABLE enroot_tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plant_id INTEGER NOT NULL
        REFERENCES enroot_plants(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER NOT NULL
        REFERENCES enroot_users(id) ON DELETE CASCADE NOT NULL,
    modified TIMESTAMP DEFAULT now() NOT NULL,
    maintenance_needed TEXT NOT NULL,
    frequency TEXT NOT NULL,
    details TEXT
);